@ECHO OFF

pushd %~dp0

REM Command file for Sphinx documentation

if "%SPHINXBUILD%" == "" (
	set SPHINXBUILD=sphinx-build
)
if "%CMAKE%" == "" (
	set CMAKE=cmake
)
set SOURCEDIR=.
set BUILDDIR=_build
if "%CMAKEBUILDDIR%" == "" (
	set CMAKEBUILDDIR=%BUILDDIR%\cmake
)

%SPHINXBUILD% >NUL 2>NUL
if errorlevel 9009 (
	echo.
	echo.The 'sphinx-build' command was not found. Make sure you have Sphinx
	echo.installed, then set the SPHINXBUILD environment variable to point
	echo.to the full path of the 'sphinx-build' executable. Alternatively you
	echo.may add the Sphinx directory to PATH.
	echo.
	echo.If you don't have Sphinx installed, grab it from
	echo.https://www.sphinx-doc.org/
	exit /b 1
)

if "%1" == "" goto help

REM conf.py and the Doxygen XML consumed by breathe are generated by CMake
%CMAKE% -S ..\.. -B %CMAKEBUILDDIR% -DKAKUHEN_BUILD_DOCS=ON || goto fail
%CMAKE% --build %CMAKEBUILDDIR% --target generate_doxygen_xml || goto fail

%SPHINXBUILD% -M %1 %SOURCEDIR% %BUILDDIR% -c %CMAKEBUILDDIR%\docs\sphinx %SPHINXOPTS% %O% || goto fail
goto end

:fail
popd
exit /b 1

:help
%SPHINXBUILD% -M help %SOURCEDIR% %BUILDDIR% %SPHINXOPTS% %O%

:end
popd
